"""Analysis unique uid constraint

Revision ID: 3890e3bd86e5
Revises: 5249ca5c3558
Create Date: 2022-03-04 10:52:50.982869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3890e3bd86e5'
down_revision = '5249ca5c3558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'analysis', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis', type_='unique')
    # ### end Alembic commands ###
