"""Adding timestamps to Analyasis

Revision ID: 5249ca5c3558
Revises: a0862062fc39
Create Date: 2022-03-04 10:06:13.483365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5249ca5c3558'
down_revision = 'a0862062fc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('analysis', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'updated_at')
    op.drop_column('analysis', 'created_at')
    # ### end Alembic commands ###
