name: Cleanup Untagged Images

on:
  # every sunday at 00:00
  schedule:
    - cron: "0 0 * * SUN"
  # or manually
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: Logora
          name: logora-nlp
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-keep-latest: 3