name: Deploy master
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-3
    
    - name: Setup ECS CLI
      uses: marocchino/setup-ecs-cli@v1
      with:
        version: "v1.18.0"

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build and push image to ECR
      env:
        ECR_REGISTRY: 812844034365.dkr.ecr.eu-west-3.amazonaws.com
        ECR_REPOSITORY: logora-nlp-production
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Create .env file
      uses: shine1594/secrets-to-env-action@master
      with:
        secrets: ${{ toJSON(secrets) }}
        secrets_env: production
        prefix_prod: _PROD_

    - name: Add image version to environment variables
      run: echo -e "\nIMAGE_VERSION=${{ github.sha }}" >> .env

    - name: Rename docker-compose web file
      run: cp docker-compose.production.yml docker-compose.yml

    - name: Create task definition version
      run: ecs-cli compose -r eu-west-3 -p nlp-production create

    - name: Setup Terraform  
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init, switch workspace and validate
      env:
        WORKSPACE: production
      run: |
        terraform init
        terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
        terraform validate -no-color
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform