name: Deploy to container registry
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      env:
        IMAGE_NAME: ghcr.io/logora/logora-nlp
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:latest
    
    - name: Create .env file
      uses: shine1594/secrets-to-env-action@master
      with:
        secrets: ${{ toJSON(secrets) }}
        secrets_env: production
        prefix_prod: "_PROD_"

    - name: Set up kubectl
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.1/bin/linux/amd64/kubectl
        chmod u+x kubectl && sudo mv kubectl /bin/kubectl

    - name: Configure Kubernetes Config
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Create Image Pull Secret
      run: |
        kubectl create namespace nlp || echo "namespace already exists"
        kubectl delete secret ghcr-login-secret --namespace nlp --ignore-not-found
        kubectl create secret docker-registry ghcr-login-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GHCR_TOKEN }} \
          --namespace nlp

    - name: Deploy to production
      run: |
        kubectl delete secret generic prod-secrets --ignore-not-found --namespace=nlp
        kubectl create secret generic prod-secrets --from-env-file=.env --namespace=nlp
        kubectl apply -R -f kubernetes/production
        kubectl rollout restart deployment nlp-production --namespace=nlp
